
# html lang
language: en

# main menu navigation
menu:
  首页: index.html
  归档: archives
  专题: subject
  标签: tags
  分类: categories
  关于: about

social:
  GitHub: https://github.com/xie-zhichao

# Google analytics
google_analytics:
# Baidu tongji
baidu_analytics: 53c2fc6d798b4e091e3315bd76a5634c
# Disqus
disqus_shortname:
# Uyan
uyan_id:
# jiaThis id
# if you want to change the style of jiaThis, please go to chage the following file:
# theme/random/layouts/includes/jiathis.swig
jiaThis_uid: 
jiathisConfig:
  data_track_clickback: true
  summary: ""
  showClose: true
  shortUrl: false
  hideMore: false



# Miscelaneous
favicon: /favicon.png

# stylesheets loaded in the <head>
stylesheets:
- /css/random.css
- //libs.cdnjs.net/vegas/2.2.0/vegas.min.css
- //libs.cdnjs.net/highlight.js/9.3.0/styles/railscasts.min.css
- //libs.cdnjs.net/fancybox/2.1.5/jquery.fancybox.min.css
- /css/iconfont/iconfont.css
- //libs.cdnjs.net/fancybox/2.1.5/helpers/jquery.fancybox-thumbs.css
- //libs.cdnjs.net/plyr/2.0.1/plyr.css

# scripts loaded in the end of the body
scripts:
- //libs.cdnjs.net/jquery/2.2.3/jquery.js
- //libs.cdnjs.net/vegas/2.2.0/vegas.min.js
- /js/random.js
- //libs.cdnjs.net/highlight.js/9.3.0/highlight.min.js
- //libs.cdnjs.net/jquery-mousewheel/3.0.6/jquery.mousewheel.min.js
- //libs.cdnjs.net/fancybox/2.1.5//jquery.fancybox.pack.js
- //libs.cdnjs.net/fancybox/2.1.5/helpers/jquery.fancybox-thumbs.js
- //libs.cdnjs.net/plyr/2.0.1/plyr.js

# ignore visitor statistics on special server, for example on you local computer or debugging server
isIgnoreSpecialHostVisitor: true
ignoreHostList:
  - localhost
  - 127.0.0.1

# if you want to turn off the background images, pleaase set this value as true
turnoffBackgroundImage: 
  # home page
  index: false
  # arcihve / categories / tags
  post_list: false
  # post and page
  post: true
# when you turn off backgrounds, you can set a background color.
backgroundColor: 34495E
 
backgroundImages:
# - http://7te9fe.com1.z0.glb.clouddn.com/bgimg_1.jpg?imageView2/1/w/__width__/h/__height__
# - http://7te9fe.com1.z0.glb.clouddn.com/bgimg_2.jpg?imageView2/1/w/__width__/h/__height__
# - http://7te9fe.com1.z0.glb.clouddn.com/bgimg_3.jpg?imageView2/1/w/__width__/h/__height__
# - http://7te9fe.com1.z0.glb.clouddn.com/bgimg_4.jpg?imageView2/1/w/__width__/h/__height__
# - http://7te9fe.com1.z0.glb.clouddn.com/bgimg_5.jpg?imageView2/1/w/__width__/h/__height__

vegasConfig:
  # more about config http://vegas.jaysalvat.com/documentation/settings/
  # animation: 'random'
  # transition: 'swirlRight'
  preload­Image: true
  transition:
    - slideLeft2
    - slideRight2
    # - zoomIn
    # - swirLeft
    # - swirRight
    # - flash
    - flash2
  timer: true
  delay: 5000
  shuffle: true
  count: 28

unsplashConfig:
  # more about config on https://unsplash.it/
  # blur: true
  gravity: 'north' # north, east, south, west, center
  # greyscale: true

avatar: /me.png

# do not like fancybox, set this as false, this will turn it off
fancybox: true

# set the visibility of hide button in left bottom.
hideButtonVisibility: true